language: go

go:
  - 1.6
  - 1.7
  - 1.8

os:
  - linux
  - osx

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/golang/lint/golint

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - go vet ./...
  - $GOPATH/bin/golint .
  - go test -cpu=2 -race -v ./...
  - go test -cpu=2 -covermode=atomic ./...
